### ISSUE TITLE
Potentially Duplicate GUID's

### ISSUE THREAD

**Issue by josephwegner** [keen/common-web#22]
I noticed this problem on my personal blog (where I do not yet use common-web), but it has now got me worried that this issue could be coming up for common-web users as well.

This graph is of newVisitors (no pre-existing GUID in a cookie) that were given a specific GUID (ie: they all received the same "random" GUID). It's over 6 months, grouped daily:

![screen shot 2015-04-06 at 9 10 57 am](https://cloud.githubusercontent.com/assets/657707/7005383/247f4e68-dc3d-11e4-9fcd-096dfaf399e5.png)

So something happened in December that started making my random GUID's not random anymore. Peaking at 57 dupes in a day, that's about 75% of my usual new visitors per day.

Unfortunately, I don't track any user-specific details (privacy! hurrah!) so I can't narrow this down to any locale/browser/etc. demographics.

I generate GUIDs with this code:

```
	function randomString() {
		var text = "";
	    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

	    for( var i=0; i < 50; i++ )
	        text += possible.charAt(Math.floor(Math.random() * possible.length));

	    return text;
	}
```

It's not exactly the same as CommonWeb's method, but they both rely on `Math.random()` for the uniqueness.

Anyways, the issue pretty much _has_ to be in `Math.random()` - for some reason it must not be seeding correctly. Some basic google research is showing some issues with `Math.random` in Chrome, but that was back in 2011. I can't find anything newer, but obviously something is up.

@hex337 @lexicography @dustinlarimer do you guys have any sites running common-web at scale, that have the latest guid update in them? It'd be great if we could poke around that data to see if you guys are seeing duplicate guids, and perhaps if you can narrow down to any demographics.

**Comment by josephwegner** [comment]
I've temporarily increased the scope of my website's analytics to try and track this down. There's a Keen API URL in this post, if you guys want to play with the data:

http://wegnerdesign.com/ramblings/temporarily-tracking-user-agents/

**Comment by hex337** [comment]
Hrm... duplicate GUID's is bad news indeed. I'll see if I can dig in as well.

**Comment by josephwegner** [comment]
@hex337 

sorry - I forgot to post an update.

I turned on some additional tracking on my website earlier to see if I could find a trend. It was Googlebot, every time. For whatever reason their bot must use the same seed for `Math.random` for every crawl.

I don't think we need to make any code-level change for this in CommonWeb, since the user agent should also be getting tracked, and that makes the issue pretty clear. We should be intentional, however, whenever we build a visualizer for CommonWeb that we filter out Spider traffic.

I'm going to close the issue, but feel free to reopen if anyone things we should make a change based on this.

**Comment by timfalls** [comment]
Thanks for all the work sleuthing this out, Joe! Awesome :)

On Monday, April 6, 2015, Joe Wegner <notifications@github.com> wrote:

> @hex337 <https://github.com/hex337>
>
> sorry - I forgot to post an update.
>
> I turned on some additional tracking on my website earlier to see if I
> could find a trend. It was Googlebot, every time. For whatever reason their
> bot must use the same seed for Math.random for every crawl.
>
> I don't think we need to make any code-level change for this in CommonWeb,
> since the user agent should also be getting tracked, and that makes the
> issue pretty clear. We should be intentional, however, whenever we build a
> visualizer for CommonWeb that we filter out Spider traffic.
>
> I'm going to close the issue, but feel free to reopen if anyone things we
> should make a change based on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keen/common-web/issues/22#issuecomment-90228443>.
>


-- 
#mobilemail
