### ISSUE TITLE
Tracking repeat visits.

### ISSUE THREAD

**Issue by fwl** [keen/common-web#8]
What are your recommendations for tracking repeat visits with common-web?

**Comment by josephwegner** [comment]
+1 this seems like something Common-Web should take care of.

It's pretty simple to drop in a unique tracking cookie.

Perhaps the interface would just be:

```
CommonWeb.trackSession()
```

That would get/set the GUID, and then update an internal global property for all events.

**Comment by dzello** [comment]
+1

That'd be really great
